JCN 313 actualizar package
janis-commerce/sls-api-upload pull request #6
Opened 2020-11-05 15:08 UTC by gastonpereyra

**LINK AL TICKET**
https://fizzmod.atlassian.net/browse/JCN-313

**DESCRIPCIÓN DEL REQUERIMIENTO**

Actualmente el package https://github.com/janis-commerce/sls-api-upload  permite subir un archivo a un bucket de S3, gettearlos individual y como listado, y borrarlos.

Pero no contiene hooks (como los de API-Save-Data), ni puede formatearse de manera custom y esto hace que su posibilidades de uso sean limitadas

Requerimiento:
* Crear los hooks faltantes en la API Post (Relation), es decir `postSaveHook`
* Crear los hooks de `postValidateHook`, para todos las API que lo necesiten, que sirva para chequeos extras.
* Agregar la posibilidad de tener nuevos `formats`, para poder realizar modificaciones custom a los datos de los archivos cuando se necesiten

**DESCRIPCIÓN DE LA SOLUCIÓN**
* Se desarrollaron los requerimientos solicitados.
* Se mejoró el README.
* En la API de Listado se agregan métodos para agregar filtros y ordenamiento de manera mas limpia, y se cambió la forma de agregar la URL a los objetos
* En las API de Listado y  GET, se agregaron 2 formats, uno para los datos  en general y uno especifico para la URL

2020-11-06 17:33 UTC, maguimarijuan requested changes

2020-11-06 17:33 UTC, maguimarijuan commented on CHANGELOG.md
> +- Every API Module, validates Bucket in `validate()` method. Now if fails finsh with `status-code: 400`
Tenes un tipo acá en finsh, capaz podes poner algo como: _If validation fails it sets status code 400_

2020-11-06 17:33 UTC, maguimarijuan commented on lib/sls-api-file-get.js
> +			return null;
No entiendo cuándo este return null se ejecuta :thinking:

2020-11-06 17:33 UTC, maguimarijuan commented on lib/sls-api-file-get.js
> +			return null;
Supongo que cuando el error no es 404. Creo que queda más claro si lo ponemos dentro del catch :thinking: no sé qué opinas?

2020-11-06 17:33 UTC, maguimarijuan commented on lib/sls-api-file-list.js
> +			...this.customSortableFields
Se me ocurre: ¿qué pasaría si el usuario no settea un array? 
Capaz podemos hacer algo así: 
```js
 const customSortableFilds = this.customSortableFields && Array.isArray(this.customSortableFields) ? this.customSortableFields : [];
  return {
     ...sarasa
    ...customSortableFields
  }
```

2020-11-06 17:33 UTC, maguimarijuan commented on lib/sls-api-file-list.js
> +			...this.customSortableFields
La idea sería en "pseudoprosacodigo": 
- sacar el getter que no hace nada 
- dentro del getSortableFields hacer un destructuring en función de si está ese campo y si está corroborar que sea un array. 
Es una sugerencia, capaz es mucho :stuck_out_tongue:

2020-11-06 17:33 UTC, maguimarijuan commented on lib/sls-api-file-list.js
> +	get customAvailableFilters() {
lo mismo que antes, por lo menos validar que sea un array, capaz no validar que sean objetos. :thinking:

2020-11-06 17:33 UTC, maguimarijuan commented on lib/sls-api-file-list.js
> +		return Promise.all(files.map(async ({ path, ...file }) => {
En lo personal, siento que es más legible si la función del map la ponemos con un método aparte, así:

```js
return Promise.all(file.map( file => this.formatFile(file)); 
```

2020-11-06 21:54 UTC, gastonpereyra commented on lib/sls-api-file-get.js
> +			return null;
Se ejecuta cuando el error es 404 (no encuentra el archivo). Estaba asi pensado originalmente.

Pero esta dentro del catch.. no sé a que te referis

2020-11-06 22:01 UTC, gastonpereyra commented on lib/sls-api-file-list.js
> +			...this.customSortableFields
`getSortableFields` ? destructuring ? no entendí.

El getter esta mas que nada para mantener un valor default, y poder ponerle un JS-Docs que aclaré que tiene que retornar un array, para que no se le ocurra poner cualquier cosa.

Pero si podría chequear que sea un array y tirar un error mas custom y amistoso

2020-11-09 14:11 UTC, maguimarijuan commented on lib/sls-api-file-get.js
> +			return null;
vi mal jajaj perdón!

2020-11-09 14:30 UTC, maguimarijuan approved these changes

2020-11-10 16:46 UTC, juanhapes requested changes

2020-11-10 16:46 UTC, juanhapes commented on lib/sls-api-file-list.js
> +	async formatUrl(path, name) {
Este `formatUrl()` es 100% igual al del **API Get**

Aprovechemos para reutilizar!

2020-11-10 17:41 UTC, merged