Add expiration options when getting credentials
janis-commerce/sls-api-upload pull request #7
Opened 2023-02-16 18:14 UTC by moruezabal

Links

[Tarea](https://janiscommerce.atlassian.net/browse/JSS-6) / [Subtarea](https://janiscommerce.atlassian.net/browse/JSS-10)

**Descripción:** 

Como se explica en https://janiscommerce.atlassian.net/browse/JSS-6 , se agregó una propiedad para determinar el LifeCycle de cada archivo. Hay que incorporar esta property en el  https://github.com/janis-commerce/sls-api-upload#slsapiupload al momento de getear las credenciales para que al llamar la lambda en Storage este dato persista.

**Análisis funcional:**

Debido a los cambios en la lambda en janis-storage , las modificación a realizar son:

En la API sls-api-file-get-credentials.js:

- Se añade la property: fileExpiration  → string -> valores que acepta son: 'oneDay' , 'tenDays', 'monthly', 'never'

- Se modifica el nombre de la propiedad expiration -> credentialExpiration para evitar confusiones

2023-03-13 21:34 UTC, Nataniel4 requested changes
Detalles a revisar!

2023-03-13 21:34 UTC, Nataniel4 commented on lib/sls-api-file-relation.js
> +	monthly: 30,
Mmmm `monthly` seria "mensual" pero en el sentido de algo que se repite mensualmente, esto es para la expiración del archivo, creo que seria "month" porque dura un mes

2023-03-13 21:34 UTC, Nataniel4 commented on lib/sls-api-file-relation.js
> +const DEFAULT_EXPIRATION_FILE = 'tenDays';
`const DEFAULT_EXPIRATION_FILE = EXPIRATION_FILE_OPTIONS.tenDays;` 🤓

2023-03-13 21:34 UTC, Nataniel4 commented on lib/sls-api-file-relation.js
> +		const expirationDate = this.getExpirationDate(expirationOption);
Si no usas expirationOption en otro lado que como parámetro para `this.getExpirationDate` tonce pasale el `expiration` como parámetro y que el metodo sea el que saque el `expirationOption`, asi la variable muere ahi y ademas no mezclamos cosas que podrian estar "aisladas" en metodos

2023-03-13 21:34 UTC, Nataniel4 commented on lib/sls-api-file-relation.js
> +		if(expirationOption === 'never')
`if(expirationOption === EXPIRATION_FILE_OPTIONS.never)`

Aca se cumple el mismo concepto de usar los `statuses` en Model 😌 no hardcodear los strings si no usar directamente el valor seteado en el objeto

2023-03-16 14:09 UTC, moruezabal commented on lib/sls-api-file-relation.js
> +const DEFAULT_EXPIRATION_FILE = 'tenDays';
Acá en realidad el valor default es 'tenDays' porque le indica en que key del objeto EXPIRATION_FILE_OPTIONS extraer el valor

2023-03-16 14:12 UTC, moruezabal commented on lib/sls-api-file-relation.js
> +	monthly: 30,
Modificado, voy a modificar también en el servicio de Storage, que tiene estas mismas opciones en las lambdas que se invocan aquí

2023-03-16 14:19 UTC, moruezabal commented
Agregadadas dos funcionalidades que se explican en la descripción del ticket.
- Un index en el modelo `baseFileModel` para expirar los archivos en la fecha indicada
- Getters en las APIS de sls-api-file-relation y sls-api-file-get-credentials para la expiración del archivo 
 -- Para setrar la expiración, la prioridad será;
- Si existe el getter, usarlo
- sino buscar en el parametro
- sino  defaul

2023-03-17 21:39 UTC, Nataniel4 requested changes

2023-03-17 21:39 UTC, Nataniel4 commented on lib/sls-api-file-get-credentials.js
> +	get fileExpiration() {
Si el valor de este getter por default es `undefined` no hace falta que lo declares en la clase, directamente cuando lo uses, si no esta establecido su valor sera `undefined` con que este documentado en el readme es suficiente (aplica en los casos donde se repita)

2023-03-17 21:39 UTC, Nataniel4 commented on lib/sls-api-file-relation.js
> +const DEFAULT_EXPIRATION_FILE = 'tenDays';
Si, pero si esto lo vas a usar mas adelante de esta forma:
```js
const expirationOption = EXPIRATION_FILE_OPTIONS[this.fileExpiration] || EXPIRATION_FILE_OPTIONS[expiration] || EXPIRATION_FILE_OPTIONS[DEFAULT_EXPIRATION_FILE];
```

Si usas `const DEFAULT_EXPIRATION_FILE = EXPIRATION_FILE_OPTIONS.tenDays;`

Podes simplificarlo:
```js
const expirationOption = EXPIRATION_FILE_OPTIONS[this.fileExpiration || expiration] || DEFAULT_EXPIRATION_FILE;
```

2023-03-22 13:04 UTC, Nataniel4 approved these changes

2023-03-23 16:49 UTC, gastonpereyra approved these changes

2023-03-31 04:46 UTC, merged